### ISSUE TITLE
Explain the `NA` values for source_id

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#37]
From Sam: 
> There are 1585692 observations where source_id is NA. Where did these data come from?

**Comment by lindsayplatt** [comment]
We used the `lake-temp/lake-temperature-model-prep/7b_temp_merge/out/temp_data_with_sources.feather` file and then [filtered](https://github.com/USGS-R/lake-temp-lstm-static-data-release/blob/main/src/prep_helpers.R#L234-L248) based on earliest date in our meteo data and whether the lake was actually modeled in our release.

**Comment by padilla410** [comment]
The lakes where `source_id` is `NA` come from a number of sources. The heart of this issue is missing values in `7b_temp_merge/in/source_metadata.csv` that result in a failed join.

`source_id` is added [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7b_temp_merge.yml#L58-L62) and it depends on `7b_temp_merge/out/merged_temp_data_daily.feather` and `7b_temp_merge/in/source_metadata.csv`. Within `add_source_ids` the two upstream files get joined together [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7b_temp_merge/src/munge_source_ids.R#L28-L30).

Here is an example of the problem:
```
library(arrow)
library(tidyverse)

# Checkout the offending file - data with missing `source_id` values
temp_dat_with_src <- read_feather("7b_temp_merge/out/temp_data_with_sources.feather")
na_temp_dat_with_src <- file |> filter(is.na(source_id))

# Checkout and and join the two files that `7b_temp_merge/out/temp_data_with_sources.feather` depends on
temp_dat <- read_feather("7b_temp_merge/out/merged_temp_data_daily.feather") |> 
  mutate(file_name = gsub('(7a_temp_coop_munge/tmp/)(.*)(.rds)', '\\2', source, perl = TRUE)) # nabbed from https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7b_temp_merge/src/munge_source_ids.R#L29
source_meta <- readr::read_csv("7b_temp_merge/in/source_metadata.csv")

comb <- left_join(temp_dat, source_meta, by = "file_name")
na_comb <- comb |> filter(is.na(source_id))
```

**Comment by padilla410** [comment]
I'm responsible for a chunk of the cooperator data sets. I can resolve the cooperator issues but it will take some time.

**Comment by lindsayplatt** [comment]
That `source_metadata.csv` file originates from the Google Drive folder `6_temp_coop_fetch/explain`, see it [here](https://docs.google.com/spreadsheets/d/1gX9ejUr18_w4mYTCORj0_ZuXdyqUhcZvpsV5G0Yu26U/edit?usp=sharing). It is downloaded as a step in the pipeline from that `6_temp_coop_fetch` location [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/bd97d8701ca1a958bbebd2f47cc6bc09b4cd939a/7b_temp_merge.yml#L45-L54). So, it is manually created and includes the info about whether or not we had permission to share the observations.

It must be that the file names in `source_metadata.csv` are not matching the filenames we have?

**Comment by padilla410** [comment]
You're correct - it's a manual update thing. 

For the cooperator data, I think I (and maybe Jordan) must have missed a few metadata updates when processing data (I took a brief look last night). For the WQP data - I am not sure why that is not matching! There is a record in that spreadsheet for `wqp` tagged datasets but it is not parsing correctly (I did not run down the "why" on that one).

**Comment by padilla410** [comment]
Updates:
* I have updated the metadata. I assumed that the 18 cooperator files I added were all available for public release
* There is a bug at [this](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7b_temp_merge/src/munge_source_ids.R#L48-L49) line of code in the temperature pipeline. The metadata.csv file has a line for WQP data where `file_name == wqp` and `source_id == wqp`, but the function does not accommodate partial matching.

**Comment by padilla410** [comment]
Update #2: fix it

Pushing up changes once everything updates

**Comment by padilla410** [comment]
We can close this issue after merging to above PR and adding the file to the HPC run of the pipeline.

**Comment by lindsayplatt** [comment]
Cool! Left one comment. Our data release pipeline depends on [`7b_temp_merge/out/temp_data_with_sources.feather`](https://github.com/USGS-R/lake-temp-lstm-static-data-release/blob/main/remake.yml#L93), so I will work on sorting that out (first pull down and build `lake-temperature-model-prep`, then build the target in this pipeline) so that it uses the appropriate updated one once the PR is merged and before we close this issue.

**Comment by lindsayplatt** [comment]
Yay! A lovely before/after for the NA sources.

```r
> sum(is.na(before$source_id))
[1] 1585692
> sum(is.na(after$source_id))
[1] 0
> nrow(before) == nrow(after)
[1] TRUE
```
