### ISSUE TITLE
Add more to the clarity definition

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#38]
This is for `lake_metadata.csv`

From Sam:
> I don’t think there’s enough information about clarity values. When did you use observed vs modeled values? If modeled, how were they modeled, and is there a citation?

**Comment by lindsayplatt** [comment]
We [joined](https://github.com/USGS-R/lake-temp-lstm-static-data-release/blob/main/src/prep_helpers.R#L113) in the clarity data file from lake-temperature-model-prep, `lake-temperature-model-prep/7_config_merge/out/nml_Kw_values.rds`. So, we will need to look to that repo's logic for explaining this.

**Comment by padilla410** [comment]
Relevant function [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7_config_merge/src/munge_lake_info.R#L36-L67)
Relevant phase [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7_config_merge.yml#L88-L93)

Based on the above function it looks like [we used observed data when possible](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7_config_merge/src/munge_lake_info.R#L42-L57) and then [filled in missing clarity info with modeled clarity](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7_config_merge/src/munge_lake_info.R#L59-L63) when possible.
