### ISSUE TITLE
Update GCM meteo inputs definition

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#46]
From Sam: 

> - “glibal” instead of “global” in the entity type definition 
> - gcm_driver – I would have named this just gcm or climate_model or something. With this name, I was expecting a variable name instead of a model name. 
> - I think you left climate data by cells because there are multiple lakes per cell, and it doesn’t make sense to repeat those values. Maybe explain this in the entity type definition? “Because cells the resolution of the downscaled climate data is x, there can be multiple lakes associated with a single cell. Data from these meteorological files can be matched to the appropriate lake…”

**Comment by lindsayplatt** [comment]
Addressed the first and last. The middle is tricky just because it could be a lot of effort to edit. However, the files are saved per GCM climate model and that value appears in the name. It probably is not necessary to also have it appear as a field in the files themselves. All in all, not a huge issue since the field has a definition that people can read.

**Comment by lindsayplatt** [comment]
> gcm_driver – I would have named this just gcm or climate_model or something. With this name, I was expecting a variable name instead of a model name.

Given that this will provide minimal improvements and that the effort to replace all the appropriate terminology could be rather large, I am not going to implement this suggestion.

**Comment by lindsayplatt** [comment]
Closed by #78

**Comment by jzwart** [comment]
agreed.
