### ISSUE TITLE
Update rain definition & revisit source attributions in GCM meteo

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#48]
From Sam:

> - Rain – the wording is a bit confusing and redundant. Maybe: “Rain reaching the lake surface in a day…” 
> - Rain and snow – again, confusing here why you’re citing Winslow et al in the description but Read 2021 in the source definition.

**Comment by jzwart** [comment]
low priority. I'd keep as is but respond with saying that Winslow describes the data processing but all datasets are from Read et al. 2021? actually not sure what Read et al. 2021 is referring to

**Comment by jzwart** [comment]
Ah, I think Winslow et al. 2017 might be a bit more appropriate for source definition citation and description. But eventually it'd all point to Winslow at some point because I assume Read et al. 2021 cites Winslow

**Comment by lindsayplatt** [comment]
You are correct. Easy enough to point to Winslow et al., 2017 here too, though.
