### ISSUE TITLE
Include more info about model requirements for why not all lakes are in all models

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#52]
From Sam:

> Once I started running the scripts to extract data from the .nc files (awesome to include these!), I quickly got confused about which lakes were in each dataset and why. In the overview section of the data release where you have the bulleted list with description, I think it would be nice to include a description of spatial coverage (in the case of the met drivers) or data requirements (in terms of the modeling approaches).

**Comment by jzwart** [comment]
high priority and partially resolved already? should be quick to include some descriptions

**Comment by lindsayplatt** [comment]
Closed by #76 + #80
