### ISSUE TITLE
Update definitions for lake temp metrics files

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#54]
From Sam:

> - In several metrics, you use “surface” and “bottom”. How are these defined? Somewhere I see that bottom was 0.1m from the bottom, is that true for all metrics? 
> - height_6.4_11.8 and other “height” metrics – if I’m interpreting this right, “water column height” might be useful words to use the in the definition 
> - Kind of confused how the “height” and “volume” metrics are computed for annual values. Are the daily values summed? There are really high height values (e.g., 14k) so I assume it’s summed somewhere. 

Explain the NAs. From Sam:
> - Reasons for NA values varies across metrics, and I think it’s worth explaining why for a majority of them. E.g. --  example winter_dur_0_4 there are 210799 NAs. Is that because it’s looking backwards, and there aren’t previous dates through October? Can you say why there would be NA values?  There are 63k NAs for coef_var variables and ice_off dates – I’m guessing those are for lake-years where there is no ice, but ice_on is years with no ice + start years where you can’t look backwards? Anyway, it would be good to know how to interpret all of these.  
> - Some NA values in mean_bottom_{dec, jan, feb} – why NA values here? (seen in `lake_temp_metrics_GLM_NLDAS.csv`)
> - Why are the NA values for mean_epi_vol when there aren’t any NA values in stratification? Is this NA for years with <30 days of stratification? Should say so since “longest stratification duration” suggests this could be any amount of time.  (seen in `lake_temp_metrics_GLM_NLDAS.csv`)

**Comment by lindsayplatt** [comment]
Discovered some `-Inf` values. Not sure why those would pop up and need to think about what they mean. 

```r
library(tidyverse)
metrics_nldas <- read_csv('out_data/lake_temperature_metrics_GLM_NLDAS.csv')
metrics_gcm <- read_csv('out_data/lake_temperature_metrics_GLM_GCM.csv')
is_negative <- function(vals) any(vals < 0)

metrics_nldas %>% 
  select(starts_with('max_bot'), starts_with('mean_bot')) %>% 
  select_if(is_negative) %>% 
  summary()
  max_bot_dec      max_bot_feb      max_bot_jan    
 Min.   :  -Inf   Min.   :  -Inf   Min.   :  -Inf  
 1st Qu.: 3.886   1st Qu.: 4.196   1st Qu.: 4.172  
 Median : 4.249   Median : 4.279   Median : 4.253  
 Mean   :  -Inf   Mean   :  -Inf   Mean   :  -Inf  
 3rd Qu.: 4.425   3rd Qu.: 4.424   3rd Qu.: 4.372  
 Max.   :20.589   Max.   :20.782   Max.   :18.852  

metrics_gcm %>% 
  select(starts_with('max_bot'), starts_with('mean_bot')) %>% 
  select_if(is_negative) %>% 
  summary()
  max_bot_dec      max_bot_feb      max_bot_jan      max_bot_mar      max_bot_may    
 Min.   :  -Inf   Min.   :  -Inf   Min.   :  -Inf   Min.   :  -Inf   Min.   :  -Inf  
 1st Qu.: 3.702   1st Qu.: 4.020   1st Qu.: 3.626   1st Qu.: 4.241   1st Qu.: 8.908  
 Median : 4.253   Median : 4.251   Median : 4.226   Median : 4.408   Median :13.775  
 Mean   :  -Inf   Mean   :  -Inf   Mean   :  -Inf   Mean   :  -Inf   Mean   :  -Inf  
 3rd Qu.: 4.617   3rd Qu.: 4.394   3rd Qu.: 4.352   3rd Qu.: 5.391   3rd Qu.:18.254  
 Max.   :24.997   Max.   :24.663   Max.   :25.045   Max.   :29.161   Max.   :36.480  
```

**Comment by jzwart** [comment]
high priority. seems like a lot of these can be easily clarified via text. would be good to take a quick look at the -Inf and NA's for metrics.csv files to see when / where they occur.

**Comment by lindsayplatt** [comment]
> In several metrics, you use “surface” and “bottom”. How are these defined? Somewhere I see that bottom was 0.1m from the bottom, is that true for all metrics?
Correct, "bottom" was [calculated as 0.1m from the bottom](https://github.com/USGS-R/lake-temperature-out/blob/main/3_summarize/src/annual_thermal_metrics.R#L504-L508) and used consistently throughout the metrics. Added this information to the definitions for `mean_{depth}_JulAugSep`, `max_{depth}_JulAugSep`, `mean_{depth}_{month}`, and `max_{depth}_{month}`

> height_6.4_11.8 and other “height” metrics – if I’m interpreting this right, “water column height” might be useful words to use the in the definition
Correct, this was easy enough to add. I replaced `Meters of water between` with `Meters of the water column between` and `Volume of water between` with `Volume of the waterbody between`

> Kind of confused how the “height” and “volume” metrics are computed for annual values. Are the daily values summed? There are really high height values (e.g., 14k) so I assume it’s summed somewhere.
Yes, these are [sums of daily values](https://github.com/USGS-R/lake-temperature-out/blob/main/3_summarize/src/annual_thermal_metrics.R#L373) to get an annual total. I've added this clarification to all of these definitions. Changes to the definitions from the previous update:

before | after
-- | --
Meters of the water column between | Annual sum of the daily water column height between
Volume of the waterbody between | Annual sum of the daily waterbody volume

**Comment by lindsayplatt** [comment]
Just noticed that I am missing an explanation for `date_below_5` entirely!!! This is a note to remind me to do that.

**Comment by lindsayplatt** [comment]
> Reasons for NA values varies across metrics, and I think it’s worth explaining why for a majority of them. E.g. -- example winter_dur_0_4 there are 210799 NAs. Is that because it’s looking backwards, and there aren’t previous dates through October? Can you say why there would be NA values? There are 63k NAs for coef_var variables and ice_off dates – I’m guessing those are for lake-years where there is no ice, but ice_on is years with no ice + start years where you can’t look backwards? Anyway, it would be good to know how to interpret all of these.

Added explanations for NAs to each of the definitions.

> Why are the NA values for mean_epi_vol when there aren’t any NA values in stratification? Is this NA for years with <30 days of stratification? Should say so since “longest stratification duration” suggests this could be any amount of time. (seen in lake_temp_metrics_GLM_NLDAS.csv)

Stratification is just the duration. `mean_epi_vol` is only calculated when  the stratified period is >= 30 days. This has been updated for the column description in the metadata.

**Comment by lindsayplatt** [comment]
> Some NA values in mean_bottom_{dec, jan, feb} – why NA values here? (seen in lake_temp_metrics_GLM_NLDAS.csv)

I also found some NAs in `mean_bot_{dec, jan, feb, mar, may}` for the GLM_GCM metrics (only 1 value in May). I suspect that this has something to do with bottom temperatures and ice but I am looking into it more deeply.

**Comment by lindsayplatt** [comment]
The mean bottom temperatures in winter can be explained by changing lake heights due to ice formation and melting in GLM. See https://github.com/USGS-R/lake-temp-lstm-static-data-release/issues/53#issuecomment-1502456974 for more info.
