### ISSUE TITLE
Oof there are a bunch of really high GCM peak temps

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#55]
From Sam:

> I think you might have filtered out observed temps >40, but there are 58k peak_temp >40 in lake_temperature_metrics_GLM_GCM.csv

**Comment by jzwart** [comment]
low priority. could respond with "we applied published models to vetted driver dataset and report all model output"

**Comment by lindsayplatt** [comment]
Replied with something along these lines in the reconciliation document.

> Yes, these high peak temperatures do exist and represent ~1% of the peak temps in this file, however, we applied published models to vetted driver datasets and are reporting all model output.
