### ISSUE TITLE
Investigate stratification metrics

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#56]
From Sam: 

> I was expecting to see some lakes that didn’t stratify, e.g., some NA values in stratification_onset_yday, especially given there are some shallow lakes in the dataset. There are also 351 0s in metric mean_epi_vol, which suggests those are lake-years that didn’t stratify? However, there are no 0 stratification_duration. Confused about how all of those things can be true at the same time.

**Comment by jzwart** [comment]
medium priority. Seems plausible to have 0 depending on the stratification metrics that were used. There might be NA values in stratification_onset_yday that weren't taken out? hard for me to understand the nuances here but I think an appropriate response would be to quickly look through how the startification metrics were applied, see if there are any obvious red flags, and then describe that you used existing models, published code, etc... and aren't reporting on the interpretation of the model output

**Comment by lindsayplatt** [comment]
We [considered a lake to be stratified if it's top and bottom temperatures differed by more than 1 deg C](https://github.com/USGS-R/lake-temperature-out/blob/main/3_summarize/src/annual_thermal_metrics.R#L534). We counted it as stratified even if the top layer was cooler than the bottom layer as long as it was > 1 deg C different. This was based on [the `mda.lakes::calc_stratified_periods()` function](https://github.com/USGS-R/mda.lakes/blob/eba6ddfba4d52c74e7b09fb1222772630dfa7f30/R/calc_stratified_periods.R).

**Comment by lindsayplatt** [comment]
Based on the definition, it does seem plausible that at least one day every year, these lakes would be considered "stratified".

**Comment by lindsayplatt** [comment]
I've added the above information to the reconciliation document.
