### ISSUE TITLE
Throw out incomplete years for metrics calcs?

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#57]
From Sam:

> Should potentially throw out metrics for start/end years if they don’t have a full year of coverage? The metrics could be misleading for those years.  

I think we may already do this? But need to check.

**Comment by jzwart** [comment]
seems easy to do if not done already

**Comment by lindsayplatt** [comment]
Shabam! We do already do this 😄 

https://github.com/USGS-R/lake-temperature-out/blob/main/3_summarize/src/annual_thermal_metrics.R#L42
