### ISSUE TITLE
Consistent terminology for meteo data

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#58]
From Sam:

> For different meteorological data, the syntax gets a bit confusing, I think because you’re talking about different models that predict lake temperature (e.g., GLM and EALSTM) and different climate models (e.g., ACCESS vs CNRM), but also different forcing datasets. Sometimes you call the met data “drivers”, sometimes “meteorological inputs”. I would suggest consistency and maybe a slight naming convention change throughout – model = temperature models, METSOURCE (or something similar) = meteorological driver source, GCM type = 6 different GCMs. For some reason, “forcings” more clearly indicates the meteorological forcings to me more clearly than “drivers”, though I recognize these are often used interchangeably.

**Comment by jzwart** [comment]
low priority. looking through the data release I don't find this confusing at all. Respond with something along the lines of "we have clearly described the different driver datasets in the data release description and all metadata accurately describe drivers throughout."

**Comment by lindsayplatt** [comment]
Added this response to the reconciliation document.
