### ISSUE TITLE
Revisit reported min/max for depth

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#61]
From Sam:

> Max depth in the lake_metadata.csv file is 148m, but the maximum reported depth in the observation file is 155

**Comment by lindsayplatt** [comment]
Hmmmm there are >3k lakes with a max observation depth greater than the reported max depth in the hypso, but only 1,308 lakes that have an observation reported over 1m deeper than the reported max depth. I see 3 options for dealing with this:

1. Update the reported max depth based on these observations (seems risky ...)
2. Filter out any obs that are more than a meter deeper than the reported max depth (would remove 32,641 observations)
3. Do nothing to the data but make a note of this in the metadata

Looking for opinions on the above @padilla410 @AndyMcAliley @hcorson-dosch-usgs 

```r
library(tidyverse)

metadata <- read_csv("out_data/lake_metadata.csv")
obs <- read_csv("tmp_data/lake_temperature_observations.csv")

# Max obs depth per site is greater than the reported max depth (+1m) in hypso
obs %>% 
  group_by(site_id) %>% 
  summarize(max_obs_depth = max(depth)) %>% 
  right_join(metadata, by = "site_id") %>% 
  select(site_id, lake_name, area, elevation, max_depth,
         max_obs_depth, num_observ) %>% 
  filter(max_obs_depth > max_depth+1)

# A tibble: 1,308 × 5
   site_id                                      lake_name            max_depth max_obs_depth num_observ
   <chr>                                        <chr>                    <dbl>         <dbl>      <dbl>
 1 nhdhr_{060CC69F-5D91-4F31-A30D-79A0723427C7} Nels Lake                 9.14          10.7        191
 2 nhdhr_{06F93A13-5AFB-4691-8F39-5140F8986BFE} NA                        9.75          11.0       3257
 3 nhdhr_{08C38C24-CCB1-4DDB-97DB-8B8973AEE01D} Siskiwit Lake            46             50         1490
 4 nhdhr_{117A9949-40FA-41DB-8E98-9479A35D2918} Laurel Lake               7.32          13.7        346
 5 nhdhr_{1DD8E60C-CDEA-421C-9135-1B1AEC740538} Spirit Lake               2.74          15.8        296
 6 nhdhr_{218860F6-696D-49C0-A4DF-AD06CCDF3077} Big Stone Lake           15.5           17.5        703
 7 nhdhr_{21D3A37A-951D-4F94-ADA3-D8823DAECCE9} Chickenbone Lake          5              6.5         60
 8 nhdhr_{281D28BC-5CA5-4391-A17C-04CF0EF71935} Little Tomahawk Lake     12.8           13.9        108
 9 nhdhr_{2B0E3504-D6DF-4C31-8F6C-6FC83A3ACE48} Gillham Lake              9.14          25.6        119
10 nhdhr_{2B16E533-E2CF-49F4-A1BE-CD65378EDEB4} Tomahawk Lake            21.3           25.6       1319
# … with 1,298 more rows


obs_depth_summary <- obs %>% 
  left_join(select(metadata, site_id, max_depth), by="site_id") %>% 
  mutate(obs_deeper_than_maxdepth = depth > (max_depth+1))
sum(obs_depth_summary$obs_deeper_than_maxdepth, na.rm=TRUE)

[1] 32641
```

**Comment by AndyMcAliley** [comment]
There was some discussion of observation depths below max depths last year. See Jordan's comments [here](https://github.com/USGS-R/lake-temperature-lstm-static/discussions/12#discussioncomment-2190638) and [here](https://github.com/USGS-R/lake-temperature-model-prep/issues/227). 

I vote for option 3, but I'm okay with option 2 also. If we choose option 2, I'd use a larger threshold than 1 m. Jordan mentions that lake depths can change by 2 m, so 2 m would be a reasonable choice of threshold.

**Comment by lindsayplatt** [comment]
Thanks for those references, @AndyMcAliley!

Based on these two points from Jordan, `lakes can swing by ~2meters between the wettest periods and the driest periods ... the highest swings are on reservoirs which can be tens of meters` and `sometimes the max depth comes from one basin but it is applied to the whole lake`, I would be extremely hesitant to do any sort of filtering. Adding information like Jordan explains in this comment would probably be the best way to do it.

**Comment by lindsayplatt** [comment]
Closing this issue since no changes are being made to the data and I've summarized these points in our review reconciliation document.
