### ISSUE TITLE
Report performance metrics for GLM & EALSTM

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#63]
Need new files?

From Sam:
> Are you reporting performance metrics for any of these models? Seems like that would be necessary to know how to use the models/know how much to trust them.

**Comment by AndyMcAliley** [comment]
If we're going to report performance metrics, then we should coordinate to report similar performance metrics for GLM and EA-LSTM. 

The EA-LSTM is trained on 60% of the lakes, validated on 20%, and tested on 20%. For each subset of lakes, I computed:
- Overal RMSE
- Median RMSE by lake
- Mean RMSE by lake

For the EA-LSTM, it's important to report the metrics for each subset, or at least the test set metrics. We've got metrics for all three subsets, so we can report them all and emphasize that the test metrics give the best estimate for model error for unobserved lakes. For GLM, though, it doesn't really matter since observations aren't used to calibrate the model. 

The bare minimum to report is the Overall RMSE for each model. We could add median RMSE and mean RMSE by lake (if it's easy to get those values for the GLM predictions).

What do you think, @hcorson-dosch-usgs? Do you think that reporting these performance metrics would suffice?

**Comment by hcorson-dosch-usgs** [comment]
Hmmm, a couple of thoughts.

1) For the GCM predictions, we can only report model bias, not model accuracy, since those models use modeled climate drivers, not actual weather drivers

2) At the moment, we are not evaluating model predictions at the lake level for either the GCM or NLDAS GLM predictions:
    * For the GCM models, we're [evaluating model bias](https://github.com/USGS-R/lake-temperature-process-models/blob/main/5_evaluate.R#L114-L135) across all successfully modeled GCM lakes w/ observations by DOY, 2-degree temperature bins, and season
    * For the NLDAS models, we're [evaluating model bias and accuracy (RMSE)](https://github.com/USGS-R/lake-temperature-process-models/blob/main/5_evaluate.R#L262-L319) across all successfully modeled NLDAS lakes w/ observations by year, DOY, 2-degree temperature bins, and season.

So if we wanted to add any lake-specific evaluation metrics we'd need to add code to do so. In that case we might want to include a summary of the # of observations/lake alongside those metrics, right?

If we decide to report only overall RMSE, I could add a target to calculate that for the NLDAS model runs. For the GCM model runs we could report average prediction bias? And here I think we'd want to report total # of lakes and total # of observations included in those calculations.

**Comment by AndyMcAliley** [comment]
I think it makes sense to stick to overall metrics rather than break it down to individual metrics for each lake. I can include number of lakes and number of observations used for the EA-LSTM metric calculations.

**Comment by AndyMcAliley** [comment]
@lindsayplatt Do you think it'd be sufficient to report overall RMSE along with the number of lakes and observations that were used to compute RMSE?

**Comment by AndyMcAliley** [comment]
RMSE of EA-LSTM predictions evaluated on test set: 2.70 °C
Number of lakes in test set: 1503
Number of temperature observations in test set: 453234

**Comment by AndyMcAliley** [comment]
Here are some seasonal metrics. I used the same day-of-year cutoffs to determine seasons as [lake-temperature-process-models](https://github.com/USGS-R/lake-temperature-process-models/blob/bb45904a17a041fa24c90bd6058fae121400dc43/5_evaluate/src/eval_utility_fxns.R#L138-L141).

| season | bias (°C) | rmse (°C) | # observations | # lakes |
|--------|-------|-------|-------|-------|
| spring |   0.302353 | 2.456292 | 130413 | 1116 |
| summer  |  0.073662 | 2.967687 | 234106 | 1400 |
| fall   |  -0.012837 | 2.380216 | 73260 | 951 |
| winter |  0.084088 | 1.617178 | 15455 | 183 |

Here's the code to get those metrics from the repo:

```python
# Compute seasonal metrics
import pandas as pd

import sys
sys.path.insert(1, '4_evaluate/src')
sys.path.insert(1, '5_visualize/src')
from plot_metrics import load_predictions, rms

predictions_filepath = "4_evaluate/out/model_prep/initial_ealstm/local_a/interpolated_predictions_test.csv"
preds = load_predictions(predictions_filepath)

preds['season'] = 'winter'
preds.loc[(preds.doy >= 60) & (preds.doy < 173), 'season'] = 'spring'
preds.loc[(preds.doy >= 173) & (preds.doy < 243), 'season'] = 'summer'
preds.loc[(preds.doy >= 243) & (preds.doy < 335), 'season'] = 'fall'

n_obs_season = preds.groupby('season')['residual'].aggregate('count')
n_lakes_season = preds.groupby('season')['site_id'].aggregate('unique').apply(len)
bias_season = preds.groupby('season')['residual'].aggregate('mean')
rmse_season = preds.groupby('season')['residual'].aggregate(rms)
```

**Comment by hcorson-dosch-usgs** [comment]
Here are csvs with evaluation metrics by season and overall metrics, for the NLDAS predictions and each set of GCM predictions: 
[evaluation_metrics_NLDAS.csv](https://github.com/USGS-R/lake-temp-lstm-static-data-release/files/11080805/evaluation_metrics_NLDAS.csv), 
[evaluation_metrics_GCM.csv](https://github.com/USGS-R/lake-temp-lstm-static-data-release/files/11080808/evaluation_metrics_GCM.csv)

code (uses the `{GCMs/NLDAS}_matched_to_observations` csvs in `'lake-temperature-process-models/5_evaluate/out'` on caldera):
```r
library(tidyverse)
library(lubridate)

munge_pred_obs <- function(pred_obs) {
  pred_obs %>%
    mutate(pred_diff = pred - obs,
           doy = yday(time),
           season = case_when(
             doy >= 60 & doy < 173 ~ 'spring',
             doy >= 173 & doy < 243 ~ 'summer',
             doy >= 243 & doy < 335 ~ 'fall',
             TRUE ~ 'winter'
           ),
           season = factor(season, levels=c('winter','spring','summer','fall')))
}

##### GCM evaluation metrics #####
gcm_pred_obs <- readr::read_csv('5_evaluate/out/Tallgrass/GCM_full_20220901/GCMs_matched_to_observations.csv', col_types = cols())

gcm_pred_obs_munged <- munge_pred_obs(gcm_pred_obs)
 
get_gcm_metrics <- function(pred_obs) {
  pred_obs %>%
    summarize(bias = mean(pred_diff, na.rm=TRUE),
              n_obs = n(),
              n_lakes = length(unique(site_id)))
}
  
evaluation_metrics_GCM_overall <- gcm_pred_obs_munged %>%
  group_by(driver) %>%
  get_gcm_metrics()

evaluation_metrics_GCM_seasonal <- gcm_pred_obs_munged %>%
  group_by(driver, season) %>%
  get_gcm_metrics()

evaluation_metrics_GCM <- bind_rows(
  mutate(evaluation_metrics_GCM_overall, season = 'overall', .after = 'driver'),
  evaluation_metrics_GCM_seasonal
)

readr::write_csv(evaluation_metrics_GCM, '5_evaluate/out/Tallgrass/evaluation_metrics_GCM.csv')

##### NLDAS evaluation metrics #####

nldas_pred_obs <- readr::read_csv('5_evaluate/out/Tallgrass/NLDAS_220826_run/NLDAS_matched_to_observations.csv', col_types = cols())

nldas_pred_obs_munged <- munge_pred_obs(nldas_pred_obs)

get_nldas_metrics <- function(pred_obs) {
  pred_obs %>%
    summarize(RMSE = sqrt(mean((pred_diff)^2, na.rm=TRUE)),
              bias = mean(pred_diff, na.rm=TRUE),
              n_obs = n(),
              n_lakes = length(unique(site_id)))
}

evaluation_metrics_nldas_overall <- nldas_pred_obs_munged %>%
  group_by(driver) %>%
  get_nldas_metrics()

evaluation_metrics_nldas_seasonal <- nldas_pred_obs_munged %>%
  group_by(driver, season) %>%
  get_nldas_metrics()

evaluation_metrics_nldas <- bind_rows(
  mutate(evaluation_metrics_nldas_overall, season = 'overall', .after = 'driver'),
  evaluation_metrics_nldas_seasonal
)

readr::write_csv(evaluation_metrics_nldas, '5_evaluate/out/Tallgrass/evaluation_metrics_NLDAS.csv')

```

**Comment by jzwart** [comment]
I think this is low priority, and I'd skip if crunched for time. You already provide observations and predictions so anyone could evaluate model for themselves. EA-LSTM and GLM are also extensively evaluated across these regions already e.g. https://aslopubs.onlinelibrary.wiley.com/doi/full/10.1002/lol2.10249 , https://www.sciencedirect.com/science/article/pii/S0304380014003664 , https://gmd.copernicus.org/articles/12/473/2019/gmd-12-473-2019.pdf

**Comment by lindsayplatt** [comment]
As Jake noted, this is low priority but the biggest chunk of work is complete because we have these files already created. Two things and I am wondering if @AndyMcAliley and @hcorson-dosch-usgs can comment on the first and potentially volunteer for the second:

1. Would it be weird to combine into a single file? The columns could be 

     - `model` (GLM or EA-LSTM)
     - `driver` (NLDAS or GCM-ACCESS, GCM-CNRM, etc)
     - `season`
     - `RMSE` (NA for all GCM rows)
     - `bias`
     - `n_obs`
     - `n_lakes`

3. We would need to add the entity/attribute information for the files. I can add the skeleton if one of you could fill in the information.

**Comment by AndyMcAliley** [comment]
1. I'm fine with combining performance metrics into a single file.
2. I could take a crack at that tomorrow. Looks like I could probably copy one of the other csvs and change the `attr-labels` to match the columns you listed.

**Comment by lindsayplatt** [comment]
@AndyMcAliley I combined and then shared some of the output (plus requested your review!) in this PR: https://github.com/USGS-R/lake-temp-lstm-static-data-release/pull/83. 

When you add the entity/attribute info, add them just above the entry for `extract_output_from_netCDFs.R` so that we can keep the metadata in the same order as the data itself will be.
