### ISSUE TITLE
Consistent reporting of min/max values

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#64]
From Sam:
> Some places you report min/max values in the metadata, some place you don’t. Maybe stay consistent? I understand you can’t when you’re using {} to write metadata for multiple metrics.

**Comment by jzwart** [comment]
Low priority, I suggest not changing metadata and respond with something like "we already report min/max where relevant and other files that have character variables and/or multiple variables"

**Comment by lindsayplatt** [comment]
Responded with this sort of sentence in the reconciliation document.
