### ISSUE TITLE
Think about moving process description into a config file

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#66]
> Process description – I wonder if providing a config file would be more useful than listing packages here? The r package renv can create a snapshot for you.

**Comment by jzwart** [comment]
lower priority and packages are already listed.  But if you do create a model code archive  #69 , could stick renv and other environments there and not in the data release

**Comment by lindsayplatt** [comment]
Since we will not be doing model code archiving, we will leave this process-description section as-is.
